### ISSUE TITLE
When signed in r/home only looks for posts in subscribed subs and not default subs.

### ISSUE THREAD

**Issue by CoreySutphin** [CoreySutphin/reddit-clone#17]

**Comment by JosephWoodside** [comment]
This is working as intended. Or do you mean when not signed in?

**Comment by CoreySutphin** [comment]
I didn't know if it was intended because If someone is not subscribed to anything their home page is empty.  We could set it up so new accounts automatically are subscribed to the defaults.

**Comment by JosephWoodside** [comment]
That's the best way I think. Reddit used to do it that way. Will implement.
